### ISSUE TITLE
[BUG] Not compatible with bevy 0.9

### ISSUE THREAD

**Issue by MTRNord** [jewlexx/bevy-discord-rpc#3]
**Describe the bug**
It seems like there are some implementations for bevy 0.9 missing:

```
◇[fedora-toolbox] ➜  conductor_sim git:(main) ✗ cargo clippy
    Checking bevy-discord-presence v0.4.0 (https://github.com/jewlexx/bevy-discord-rpc.git?branch=trunk#b4779a70)
error[E0277]: the trait bound `ActivityState: Resource` is not satisfied
   --> /home/marcel/.cargo/git/checkouts/bevy-discord-rpc-0eb70d3fe797e6c1/b4779a7/src/lib.rs:67:19
    |
67  |     mut activity: ResMut<ActivityState>,
    |                   ^^^^^^^^^^^^^^^^^^^^^ the trait `Resource` is not implemented for `ActivityState`
    |
    = help: the following other types implement trait `Resource`:
              AmbientLight
              AppTypeRegistry
              AssetServer
              Assets<T>
              Audio<Source>
              Axis<T>
              ClearColor
              ComponentUniforms<C>
            and 83 others
note: required by a bound in `bevy::prelude::ResMut`
   --> /home/marcel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/change_detection.rs:243:35
    |
243 | pub struct ResMut<'a, T: ?Sized + Resource> {
    |                                   ^^^^^^^^ required by this bound in `ResMut`

error[E0277]: the trait bound `Client: Resource` is not satisfied
   --> /home/marcel/.cargo/git/checkouts/bevy-discord-rpc-0eb70d3fe797e6c1/b4779a7/src/lib.rs:68:17
    |
68  |     mut client: ResMut<Client>,
    |                 ^^^^^^^^^^^^^^ the trait `Resource` is not implemented for `Client`
    |
    = help: the following other types implement trait `Resource`:
              AmbientLight
              AppTypeRegistry
              AssetServer
              Assets<T>
              Audio<Source>
              Axis<T>
              ClearColor
              ComponentUniforms<C>
            and 83 others
note: required by a bound in `bevy::prelude::ResMut`
   --> /home/marcel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/change_detection.rs:243:35
    |
243 | pub struct ResMut<'a, T: ?Sized + Resource> {
    |                                   ^^^^^^^^ required by this bound in `ResMut`

error[E0277]: the trait bound `RPCConfig: Resource` is not satisfied
   --> /home/marcel/.cargo/git/checkouts/bevy-discord-rpc-0eb70d3fe797e6c1/b4779a7/src/lib.rs:69:13
    |
69  |     config: Res<RPCConfig>,
    |             ^^^^^^^^^^^^^^ the trait `Resource` is not implemented for `RPCConfig`
    |
    = help: the following other types implement trait `Resource`:
              AmbientLight
              AppTypeRegistry
              AssetServer
              Assets<T>
              Audio<Source>
              Axis<T>
              ClearColor
              ComponentUniforms<C>
            and 83 others
note: required by a bound in `bevy::prelude::Res`
   --> /home/marcel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/system/system_param.rs:274:23
    |
274 | pub struct Res<'w, T: Resource> {
    |                       ^^^^^^^^ required by this bound in `Res`

error[E0277]: the trait bound `ActivityState: Resource` is not satisfied
   --> /home/marcel/.cargo/git/checkouts/bevy-discord-rpc-0eb70d3fe797e6c1/b4779a7/src/lib.rs:101:37
    |
101 | fn check_activity_changed(activity: Res<ActivityState>, mut client: ResMut<Client>) {
    |                                     ^^^^^^^^^^^^^^^^^^ the trait `Resource` is not implemented for `ActivityState`
    |
    = help: the following other types implement trait `Resource`:
              AmbientLight
              AppTypeRegistry
              AssetServer
              Assets<T>
              Audio<Source>
              Axis<T>
              ClearColor
              ComponentUniforms<C>
            and 83 others
note: required by a bound in `bevy::prelude::Res`
   --> /home/marcel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/system/system_param.rs:274:23
    |
274 | pub struct Res<'w, T: Resource> {
    |                       ^^^^^^^^ required by this bound in `Res`

error[E0277]: the trait bound `Client: Resource` is not satisfied
   --> /home/marcel/.cargo/git/checkouts/bevy-discord-rpc-0eb70d3fe797e6c1/b4779a7/src/lib.rs:101:69
    |
101 | fn check_activity_changed(activity: Res<ActivityState>, mut client: ResMut<Client>) {
    |                                                                     ^^^^^^^^^^^^^^ the trait `Resource` is not implemented for `Client`
    |
    = help: the following other types implement trait `Resource`:
              AmbientLight
              AppTypeRegistry
              AssetServer
              Assets<T>
              Audio<Source>
              Axis<T>
              ClearColor
              ComponentUniforms<C>
            and 83 others
note: required by a bound in `bevy::prelude::ResMut`
   --> /home/marcel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/change_detection.rs:243:35
    |
243 | pub struct ResMut<'a, T: ?Sized + Resource> {
    |                                   ^^^^^^^^ required by this bound in `ResMut`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `bevy-discord-presence` due to 5 previous errors
```

**To Reproduce**
Use the git version and try to build with bevy 0.9

**Expected behavior**
It compiles

**Comment by jewlexx** [comment]
Fixed in #7

**Comment by MTRNord** [comment]
Thanks for being this quick :D
